"""back to in time not multidevices

Revision ID: 8ee12b038cfd
Revises: c74c736b5943
Create Date: 2023-11-22 13:49:22.483588

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8ee12b038cfd'
down_revision: Union[str, None] = 'c74c736b5943'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_devices_id', table_name='devices')
    op.drop_table('devices')
    op.add_column('users', sa.Column('refresh_token', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'refresh_token')
    op.create_table('devices',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('device_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('refresh_token', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='devices_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='devices_pkey')
    )
    op.create_index('ix_devices_id', 'devices', ['id'], unique=False)
    # ### end Alembic commands ###
